name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential yt-dlp ffmpeg

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Copy required files
        run: |
          mkdir release
          cp build/yt-snip release/
          cp LICENSE release/ || touch release/LICENSE
          cp README.md release/

      - name: Package artifacts
        run: |
          cd release
          tar -czf ../yt-snip-linux.tar.gz ./*

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: yt-snip-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 